services:
  shuai-ubuntu-base-systemd:
    image: ${UBUNTU_BASE_SYSTEMD_IMAGE_REPO}:${UBUNTU_BASE_SYSTEMD_IMAGE_TAG}
    container_name: ${UBUNTU_BASE_SYSTEMD_CONTAINER_NAME}
    labels:
      - "maintainer=shijiashuai"
      - "description=Ubuntu Noble base with systemd"
    hostname: ${UBUNTU_BASE_SYSTEMD_CONTAINER_NAME}
    privileged: true
    restart: always
    shm_size: 16g
    ipc: host
    stdin_open: true
    tty: true
    cap_add:
      - SYS_PTRACE
    security_opt:
      - seccomp=unconfined
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - /data:/data
      - /data1:/data1
      - /data2:/data2
      - /mnt/nas1:/mnt/nas1
      - /data_melody:/data_melody
      - /data-melody:/data-melody
      - /lush_test:/lush_test
      - /data-lush:/data-lush
    environment:
      - TERM=${TERM:-xterm-256color}
      - LANG=${LANG:-en_US.UTF-8}
      - CONDA_DISABLE_PROGRESS_BARS=1