services:
  shuai-bench-test:
    image: ${BENCH_IMAGE_NAME}
    container_name: ${BENCH_CONTAINER_NAME}
    labels:
      - "maintainer=shijiashuai"
      - "description=ubuntu dev environment (supervisord)"
    hostname: ${BENCH_CONTAINER_NAME}
    restart: always
    pid: "host"
    network_mode: "host"
    privileged: true
    shm_size: 16g
    ipc: host
    cap_add:
      - ALL
    security_opt:
      - seccomp:unconfined
    stdin_open: true
    tty: true
    build:
      context: .
      dockerfile: Dockerfile
      args:
        # 用户配置
        - USER_NAME=shijiashuai
        - USER_ID=2034
        - GROUP_NAME=lush-dev
        - GROUP_ID=2000
        - USER_PASSWORD=phoenix2024
        #   - http_proxy=${HTTP_PROXY}
        #   - https_proxy=${HTTPS_PROXY}
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /data:/data
      - /data1:/data1
      - /data2:/data2
      - /mnt/nas1:/mnt/nas1
      - /data_melody:/data_melody
      - /data-melody:/data-melody
      - /lush_test:/lush_test
      - /data-lush:/data-lush
    environment:
      - TERM=${TERM}
      - LANG=${LANG}
      - CONDA_DISABLE_PROGRESS_BARS=1
    ports:
      - "${BENCH_SSH_PORT}:22"
    working_dir: /data-lush/lush-dev/shijiashuai