#
# Docker Compose for AlmaLinux HPC Development Environment
#
version: '3.8'

services:
  alma-dev:
    # -- Image & Build Configuration --
    # The image will be named 'alma-dev:latest'
    image: alma-dev:latest
    # Build context is the current directory (alma-dev)
    build:
      context: .
      dockerfile: Dockerfile
      # Pass the base image name as a build argument
      args:
        - BASE_IMAGE=alma-base:latest

    # -- Container Configuration --
    container_name: alma-dev
    hostname: alma-dev
    # Load password from .env file for use inside the container (e.g., by scripts)
    env_file:
      - .env
    # Set proxy environment variables if needed
    environment:
      http_proxy: http://172.19.11.241:443
      https_proxy: http://172.19.11.241:443
      no_proxy: localhost,127.*,10.*,172.16.*

    # -- Runtime & Security --
    # Run as the non-root user defined in the base image
    user: "2034:2000"
    # Privileged mode and capabilities for debugging tools like gdb
    privileged: true
    cap_add:
      - SYS_PTRACE
    security_opt:
      - seccomp=unconfined
    # Shared memory and IPC for high-performance applications
    shm_size: 16g
    ipc: host
    # Keep the container running
    restart: unless-stopped
    tty: true
    stdin_open: true

    # -- Networking & Volumes --
    ports:
      # Map container's SSH port 22 to host port 28974
      - "28974:22"
    volumes:
      # Mount your local workspace into the container
      - /data/lush-dev/shijiashuai/workspace:/workspace
      # Mount additional data volumes
      - /data:/data
      - /data1:/data1

    # -- Default Directory --
    working_dir: /workspace

