# 启动容器
# docker-compose up -d
# 单独标记和构建镜像
# docker build -t jiashuai/ubuntu:1.0 .

version: '3.8'
services:
  conda-bio-pkgs:
    environment:
      - LANG=${LANG:-zh_CN.UTF-8}
      - TERM=${TERM:-xterm-256color}
    container_name: ${BIO_CONDABIOPKGS_CONTAINER_NAME:-conda-bio-pkgs-tools}
    restart: "no"
    stdin_open: true
    tty: true
    build:
      context: .
      dockerfile: Dockerfile
    image: ${BIO_CONDABIOPKGS_IMAGE_REPO:-my-repo/conda-bio-pkgs}:${BIO_CONDABIOPKGS_IMAGE_TAG:-latest}
    volumes:
      - ../../data-vol:/data-vol
      - ../../git-mirrors:/git-mirrors
      - ../../HPC-Data:/HPC-Data
      - /etc/localtime:/etc/localtime:ro
    working_dir: /data
    command: ["tail", "-f", "/dev/null"]
    
