version: '3.8'

services:
  kraken2:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        LANG: ${LANG:-C.UTF-8}
        TERM: ${TERM:-xterm-256color}
        http_proxy: "${http_proxy}"
        https_proxy: "${https_proxy}"
        no_proxy: "${no_proxy}"
    image: ${BIO_METAGENOMICS_KRAKEN2_IMAGE_REPO:-my-repo/kraken2-tool}:${BIO_METAGENOMICS_KRAKEN2_IMAGE_TAG:-2.1.3}
    container_name: ${BIO_METAGENOMICS_KRAKEN2_CONTAINER_NAME:-kraken2-tool-runner} # Used by docker-compose up/start
    env_file:
      - .env # Load variables for substitution and potentially for the container if not set via Dockerfile ENV
    # command: kraken2 # Removed, as CMD is in Dockerfile. Specify command with 'docker-compose run kraken2 <command_and_args>'
    # Volumes should be mounted at runtime, e.g.:
    # volumes:
    #   - ./my_kraken_db:/kraken2-db
    #   - ./my_input_data:/data

# Removed top-level volumes, they are not used by this specific service directly here
# volumes:
#   scripts:
#     driver: local
#   data:
#     driver: local
