# 通用的安装C++环境的基础版本 
services:
  shuai-ubuntu-2404:
    image: shuai/ubuntu-2404:latest
    container_name: shuai-ubuntu-2404
    labels:
      - "maintainer=shijiashuai"
      - "description=C++/Python dev-environment"
    hostname: shuai-ubuntu-2404
    privileged: true
    restart: always
    shm_size: 16g
    ipc: host
    stdin_open: true
    tty: true
    # user: shijiashuai 去掉，和supervisord启动权限冲突
    cap_add:
      - SYS_PTRACE
    security_opt:
      - seccomp=unconfined
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - http_proxy=http://172.19.11.241:443
        - https_proxy=http://172.19.11.241:443
    volumes:
      - /data:/data
      - /data1:/data1
      - /data2:/data2
      - /data_test:/data_test
      - /mnt/nas1:/mnt/nas1
      - /data_melody:/data_melody
      - /data-melody:/data-melody
      - /lush_test:/lush_test
      - /lush-test:/lush-test
      - /data-lush:/data-lush
    environment:
      - TERM=xterm-256color
      - LANG=en_US.UTF-8
    ports:
      - "28964:22"  # SSH端口映射
    working_dir: /data-lush/lush-dev/shijiashuai
