services:
  shuai-ubuntu:
    image: shuai/ubuntu:1.0
    container_name: shuai-ubuntu
    labels:
      - "maintainer=shijiashuai"
      - "description=ubuntu 20.04 base"
    hostname: shuai-ubuntu
    privileged: true
    restart: always
    shm_size: 16g
    ipc: host
    stdin_open: true
    tty: true
    # user: shijiashuai 去掉，和supervisord启动权限冲突
    cap_add:
      - SYS_PTRACE
    security_opt:
      - seccomp=unconfined
    build:
      context: .
      dockerfile: Dockerfile
      # args:
      #   - http_proxy=http://172.19.11.241:443
      #   - https_proxy=http://172.19.11.241:443
    volumes:
      - /data:/data
      - /data1:/data1
      - /data2:/data2
      - /mnt/nas1:/mnt/nas1
      - /data_melody:/data_melody
      - /data-melody:/data-melody
      - /lush_test:/lush_test
      - /data-lush:/data-lush
    environment:
      - TERM=xterm-256color
      - LANG=en_US.UTF-8
      - CONDA_DISABLE_PROGRESS_BARS=1
    ports:
      - "28963:22"
    working_dir: /data-lush/lush-dev/shijiashuai