# 启动容器
# docker-compose up -d
# 单独标记和构建镜像
# ubuntu 22.04

version: '3.8'
services:
  bioconductor:
    labels:
      version: "1.0"
      description: "bioconductor"
    environment:
      http_proxy: http://172.19.11.241:443
      https_proxy: http://172.19.11.241:443
      no_proxy: localhost,127.*,10.*,172.16.*
    container_name: jiashuai_biodev
    hostname: bioconductor
    privileged: true
    restart: no
    # shm_size: 16g
    ipc: host
    stdin_open: true # 保持stdin开放
    tty: true
    cap_add:
      - SYS_PTRACE
    security_opt:
      - seccomp=unconfined
    build:
      context: .
      dockerfile: Dockerfile
    image: jiashuai/bioconductor:1.0
    volumes:
      - /data/lush-dev/shijiashuai/workspace:/workspace
      - /data:/data
      - /data1:/data1
    ports:
      - "28975:22"
    user: shijiashuai:lush-dev
    working_dir: /workspace
    command: ["bash"]
    
