# 启动容器
# docker-compose up -d
# 单独标记和构建镜像
# docker build -t jiashuai/centos:7.9 .

version: '3.8'
services:
  # Assuming service name might be like this, adjust if different
  shuai-centos7-dev:
    image: ${CENTOS7_IMAGE_REPO}:${CENTOS7_IMAGE_TAG}
    container_name: ${CENTOS7_CONTAINER_NAME}
    hostname: ${CENTOS7_CONTAINER_NAME}
    labels:
      version: "1.0"
      description: "CentOS 7 with C++ development tools"
    environment:
      - LANG=${LANG}
      - TERM=${TERM}
      - HTTP_PROXY=http://172.16.55.9:443
      - HTTPS_PROXY=http://172.16.55.9:443
      - NO_PROXY=localhost;127.*;10.*;172.16.*;172.17.*;172.18.*;172.19.*;172.20.*;172.21.*;172.22.*;172.23.*;172.24.*;172.25.*;172.26.*;172.27.*;172.28.*;172.29.*;172.30.*;172.31.*;192.168.*
    privileged: true
    restart: always
    shm_size: 16g
    ipc: host
    stdin_open: true # 保持stdin开放
    tty: true
    cap_add:
      - SYS_PTRACE
    security_opt:
      - seccomp=unconfined
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - USER_NAME=${CENTOS7_SSH_USER}
        - USER_PASSWORD=${CENTOS7_USER_PASSWORD}
    volumes:
      - /data/lush-dev/shijiashuai/workspace:/workspace
      - /data:/data
      - /data1:/data1
    ports:
      - "${CENTOS7_SSH_PORT}:22"
    user: 2034:2000
    working_dir: /workspace
    command: ["zsh"]
    
