services:
  shuai-ubuntu-base:
    image: shuai/ubuntu-base-systemd:latest
    container_name: shuai-ubuntu-base
    labels:
      - "maintainer=shijiashuai"
      - "description=Ubuntu Noble base with systemd"
    hostname: shuai-ubuntu-base
    privileged: true
    restart: always
    shm_size: 16g
    ipc: host
    stdin_open: true
    tty: true
    user: shijiashuai
    cap_add:
      - SYS_PTRACE
    security_opt:
      - seccomp=unconfined
    build:
      context: .
      dockerfile: Dockerfile
      # args:
      #   - http_proxy=${HTTP_PROXY}
      #   - https_proxy=${HTTPS_PROXY}
    volumes:
      - /data:/data
      - /data1:/data1
      - /data2:/data2
      - /mnt/nas1:/mnt/nas1
      - /data_melody:/data_melody
      - /data-melody:/data-melody
      - /lush_test:/lush_test
      - /data-lush:/data-lush
    environment:
      - TERM=xterm-256color
      - LANG=en_US.UTF-8
      - CONDA_DISABLE_PROGRESS_BARS=1
    # ports:
    #  - "28964:22"
    # working_dir: /home/shijiashuai