version: '3.8'
services:
  cpp-container:
    image: jiashuai/vscode/cpp-dev:ubuntu
    container_name: jiashuai.vscode.cpp-ubuntu
    # labels:
    #   - "shijiashuai"
    environment:
      http_proxy: http://172.16.55.9:443
      https_proxy: http://172.16.55.9:443
      no_proxy: localhost;127.*;10.*;172.16.*;172.17.*;172.18.*;172.19.*;172.20.*;172.21.*;172.22.*;172.23.*;172.24.*;172.25.*;172.26.*;172.27.*;172.28.*;172.29.*;172.30.*;172.31.*;192.168.*
    hostname: ubuntu_22.04
    privileged: true
    restart: always
    shm_size: 16g
    ipc: host
    stdin_open: true # 保持stdin开放
    tty: true
    cap_add:
      - SYS_PTRACE
    security_opt:
      - seccomp=unconfined
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - /data:/data
      - /data1:/data1
    ports:
      - "28965:22"
    user: shijiashuai
    working_dir: /workspace
    command: ["zsh"]
    
