# 启动容器
# docker-compose up -d
# 单独标记和构建镜像
# docker build -t jiashuai/ubuntu:1.0 .

version: '3.8'
services:
  biocontainers-dev:
    environment:
      - LANG=${LANG:-zh_CN.UTF-8}
      - TERM=${TERM:-xterm-256color}
    container_name: ${BIO_BIOCONTAINERS_CONTAINER_NAME:-biocontainers-dev-env}
    hostname: ${BIO_BIOCONTAINERS_HOSTNAME:-biocontainers-dev}
    privileged: true
    restart: "no"
    ipc: host
    stdin_open: true
    tty: true
    cap_add:
      - SYS_PTRACE
    security_opt:
      - seccomp:unconfined
    build:
      context: .
      dockerfile: Dockerfile
      args:
        SETUP_USER: ${SSH_USER_NAME:-shijiashuai}
        SETUP_USER_PASSWORD: ${USER_PASSWORD:-password}
        LANG: ${LANG:-zh_CN.UTF-8}
        TERM: ${TERM:-xterm-256color}
        ENABLE_SSH: ${ENABLE_SSH:-yes}
        SSH_PORT: "22"
        ENABLE_SUPERVISOR: ${ENABLE_SUPERVISOR:-yes}
        ENABLE_SUDO: ${ENABLE_SUDO:-yes}
        INSTALL_OH_MY_ZSH: ${INSTALL_OH_MY_ZSH:-yes}
        http_proxy: "${http_proxy}"
        https_proxy: "${https_proxy}"
        no_proxy: "${no_proxy}"
    image: ${BIO_BIOCONTAINERS_IMAGE_REPO:-my-repo/biocontainers-dev}:${BIO_BIOCONTAINERS_IMAGE_TAG:-latest}
    volumes:
      - ../../data-vol:/data-vol
      - ../../git-mirrors:/git-mirrors
      - ../../HPC-Data:/HPC-Data
      - /etc/localtime:/etc/localtime:ro
    ports:
      - "${BIO_BIOCONTAINERS_SSH_PORT:-2203}:22"
    user: ${SSH_USER_NAME:-shijiashuai}
    working_dir: /home/${SSH_USER_NAME:-shijiashuai}
    
