version: '3.8'

services:
  ubuntu-base-systemd:
    image: ${UBUNTU_BASE_SYSTEMD_IMAGE_REPO:-shuai/ubuntu-base-systemd}:${UBUNTU_BASE_SYSTEMD_IMAGE_TAG:-noble}
    container_name: ${UBUNTU_BASE_SYSTEMD_CONTAINER_NAME:-ubuntu-base-systemd-cont}
    labels:
      - "maintainer=shijiashuai"
      - "description=Ubuntu Noble base with systemd, parameterized build"
    hostname: ubuntu-base-systemd # Can be same as container_name or customized
    privileged: true # Often needed for full systemd functionality
    # restart: no # Or remove if not needed
    # shm_size: 16g # Retained from original, adjust if necessary
    # ipc: host # Retained from original, consider if essential for base image testing
    stdin_open: true
    tty: true
    # user: shijiashuai # Removed: User not created in this base Dockerfile
    # cap_add: # Retained from original, review if needed for base image
    #   - SYS_PTRACE
    # security_opt: # Retained from original, review if needed for base image
    #   - seccomp:unconfined
    build:
      context: .
      dockerfile: Dockerfile
      args:
        LANG: ${LANG:-en_US.UTF-8} # From .env or default
        TERM: ${TERM:-xterm-256color} # From .env or default
        # Proxies are passed if set in the shell environment running docker-compose
        http_proxy: "${http_proxy}"
        https_proxy: "${https_proxy}"
        no_proxy: "${no_proxy}"
    volumes:
      # Example volume, adjust as needed for testing the base image
      - /data:/data
      # - /data1:/data1 # Original, commented out
      # - /data2:/data2 # Original, commented out
      # - /mnt/nas1:/mnt/nas1 # Original, commented out
      # - /data_melody:/data_melody # Original, commented out
      # - /data-melody:/data-melody # Original, commented out
      # - /lush_test:/lush_test # Original, commented out
      # - /data-lush:/data-lush # Original, commented out
    environment:
      # TERM and LANG are set inside the Dockerfile now via ENV using ARGs
      # These runtime environment variables can override or supplement those.
      TERM: ${TERM:-xterm-256color} # From .env or default
      LANG: ${LANG:-en_US.UTF-8}   # From .env or default
      CONDA_DISABLE_PROGRESS_BARS: "1" # Retained from original
    # ports: # No SSH service in this base image
    # working_dir: / # Or /root if exec-ing as root
    env_file:
      - .env