version: '3.8'
services:
  transformers:
    environment:
      http_proxy: http://172.19.11.241:443
      https_proxy: http://172.19.11.241:443
      no_proxy: localhost,127.*,10.*,172.16.*
    labels:
      version: "1.0"
      description: "JupyterLab test"
    image: docker.io/jupyter/tensorflow-notebook:latest
    container_name: jiashuai_jupyter
    hostname: jupyter
    privileged: true
    restart: no
    shm_size: 16g
    ipc: host
    stdin_open: true # 保持stdin开放
    tty: true
    cap_add:
      - SYS_PTRACE
    security_opt:
      - seccomp=unconfined
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - /data/lush-dev/shijiashuai/workspace:/workspace
      - /data:/data
      - /data1:/data1
    ports:
      - "28972:22"
      - "28973:8888"
    user: "shijiashuai:lush-dev"
    working_dir: /workspace
    command: ["bash"]

