# 启动容器
# docker-compose up -d
# 单独标记和构建镜像
# docker build -t jiashuai/centos:7.9 .

version: '3.8'
services:
  centos-7.9:
    labels:
      version: "1.0"
      description: "CentOS 7 with C++ development tools"
    # container_name 可以自动有规则生成，且保证是唯一的
    container_name: jiashuai.centos-7.9
    environment:
      http_proxy: http://172.16.55.9:443
      https_proxy: http://172.16.55.9:443
      no_proxy: localhost;127.*;10.*;172.16.*;172.17.*;172.18.*;172.19.*;172.20.*;172.21.*;172.22.*;172.23.*;172.24.*;172.25.*;172.26.*;172.27.*;172.28.*;172.29.*;172.30.*;172.31.*;192.168.*
    hostname: centos-7.9
    privileged: true
    restart: always
    shm_size: 16g
    ipc: host
    stdin_open: true # 保持stdin开放
    tty: true
    cap_add:
      - SYS_PTRACE
    security_opt:
      - seccomp=unconfined
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - /data/lush-dev/shijiashuai/workspace:/workspace
      - /data:/data
      - /data1:/data1
    ports:
      - "28966:22"
    user: 2034:2000
    working_dir: /workspace
    command: ["zsh"]
    
