version: '3.8'
services:
  java-dev:
    image: shuai/idea:latest
    container_name: shuai-idea
    hostname: shuai-idea
    labels:
      - "maintainer=shijiashuai"
      - "description=Java多版本开发环境(JDK 8/11/17)"
    privileged: true
    restart: always
    shm_size: 16g
    ipc: host
    stdin_open: true
    tty: true
    # user: shijiashuai 去掉，和supervisord启动权限冲突
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - http_proxy=http://172.19.11.241:443
        - https_proxy=http://172.19.11.241:443
    volumes:
      - /data:/data
      - /data1:/data1
      - /data2:/data2
      - /data_test:/data_test
      - /mnt/nas1:/mnt/nas1
      - /data_melody:/data_melody
      - /data-melody:/data-melody
      - /lush_test:/lush_test
      - /lush-test:/lush-test
      - /data-lush:/data-lush
    environment:
      - TERM=xterm-256color
      - LANG=en_US.UTF-8
    ports:
      - "28963:22"  # SSH端口映射
    working_dir: /data-lush/lush-dev/shijiashuai
