# 启动容器
# docker-compose up -d
# 单独标记和构建镜像
# docker build -t jiashuai/ubuntu:1.0 .

version: '3.8'
services:
  data-castle:
    labels:
      version: "1.0"
      description: "bio dev env"
    environment:
      - LANG=${LANG} # 使用根.env中的LANG设置
      - TERM=${TERM} # 使用根.env中的TERM设置
      - HTTP_PROXY=http://172.19.11.241:443 # 注意：此处的硬编码代理
      - HTTPS_PROXY=http://172.19.11.241:443 # 注意：此处的硬编码代理
      - NO_PROXY=localhost,127.*,10.*,172.16.*
    container_name: ${BIOCONTAINERS_CONTAINER_NAME} # 使用变量
    hostname: ${BIOCONTAINERS_HOSTNAME} # 使用变量
    privileged: true
    restart: no
    # shm_size: 16g
    ipc: host
    stdin_open: true # 保持stdin开放
    tty: true
    cap_add:
      - SYS_PTRACE
    security_opt:
      - seccomp=unconfined
    build:
      context: .
      dockerfile: Dockerfile-BioDev
    image: ${BIOCONTAINERS_IMAGE_NAME} # 使用变量
    volumes:
      - /data/lush-dev/shijiashuai/workspace:/workspace
      - /data:/data
      - /data1:/data1
    ports:
      - "${BIOCONTAINERS_SSH_PORT}:22" # 使用变量
    user: shijiashuai:lush-dev
    working_dir: /workspace
    command: ["bash"]
    
