version: '3.8'

services:
  krona:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        LANG: ${LANG:-C.UTF-8}
        TERM: ${TERM:-xterm-256color}
        http_proxy: "${http_proxy}"
        https_proxy: "${https_proxy}"
        no_proxy: "${no_proxy}"
    image: ${BIO_METAGENOMICS_KRONA_IMAGE_REPO:-my-repo/krona-tool}:${BIO_METAGENOMICS_KRONA_IMAGE_TAG:-2.8.1}
    container_name: ${BIO_METAGENOMICS_KRONA_CONTAINER_NAME:-krona-tool-runner}
    env_file:
      - .env
    command: ktImportTaxonomy
